language: java

jdk:
  - oraclejdk8

sudo: false

install: true

script:
 - pwd
 - cd webapp
 - chmod +x gradlew
 - ./gradlew build
 - ls -al
 - cd ..

after_success:
 - pwd
 - ls -al
 - mkdir codedeploy_artifact
 - cp infrastructure/aws/codedeploy/*.sh .
 - cp infrastructure/aws/codedeploy/*.yml .
 - zip -r code-deploy.csye6225-fall2018-sarpotdarg.me.zip webapp/build/libs/ROOT.war *.sh *.yml
 - ls -al
 - mv ccode-deploy.csye6225-fall2018-sarpotdarg.me.zip codedeploy_artifact/
 - ls -al
 - pwd
 - cd codedeploy_artifact
 - ls -al
 - pwd
 - cd ..
 - pwd
 - ls -al

deploy:
 - provider: s3
   local_dir: codedeploy_artifact
   bucket: $s3_bucket
   region: us-east-1
   skip_cleanup: true
   access_key_id: $access_key_id
   secret_access_key: $secret_access_key
   on:
     all_branches: true

 - provider: codedeploy
   access_key_id: $access_key_id
   secret_access_key: $secret_access_key
   bucket: $s3_bucket
   region: us-east-1
   key: csye6225-fall2018-sarpotdarg.me.zip
   bundle_type: zip
   application: $application
   deployment_group: $deployment_group
   wait-until-deployed: true
   on:
     all_branches: true
